# Generated by Django 4.2.4 on 2023-08-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Hits',
        ),
        migrations.RenameField(
            model_name='adventure',
            old_name='genre',
            new_name='developer',
        ),
        migrations.RenameField(
            model_name='puzzle',
            old_name='genre',
            new_name='developer',
        ),
        migrations.RenameField(
            model_name='rpghorror',
            old_name='genre',
            new_name='developer',
        ),
        migrations.RenameField(
            model_name='stealth',
            old_name='genre',
            new_name='developer',
        ),
        migrations.RenameField(
            model_name='survival',
            old_name='genre',
            new_name='developer',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='rpghorror',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='stealth',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='survival',
            name='publisher',
        ),
    ]
