# Generated by Django 4.2.4 on 2023-08-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_retro_delete_hits_rename_genre_adventure_developer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stealth',
        ),
        migrations.AlterField(
            model_name='adventure',
            name='developer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='mode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='platform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='developer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='mode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='platform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retro',
            name='mode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rpghorror',
            name='developer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rpghorror',
            name='mode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rpghorror',
            name='platform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rpghorror',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survival',
            name='developer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survival',
            name='mode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survival',
            name='platform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survival',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
