# Generated by Django 4.2.4 on 2023-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_delete_stealth_alter_adventure_developer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='rpghorror',
            name='mode',
        ),
    ]
