# Generated by Django 4.2.4 on 2023-08-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_stealth_remove_rpghorror_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birth_date',
        ),
    ]
